

import type { Metadata } from "next";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayout_props = {
   children: React.ReactNode;
};

export default function RootLayout( { children }: Readonly<RootLayout_props> ) {
   return( <>
      {/* <ClerkProvider> */}
         <html lang="en">
            <body className={`
               ${geistSans.variable} ${geistMono.variable} antialiased
            `} >

               { children }
            </body>
         </html>
      {/* </ClerkProvider> */}
   </> );
}
